version: '3.9'

services:
  logserver:
    image: htetlinmaung/logserver
    build: .
    ports:
      - "9999:3000"
    environment:
      - connection_string=mongodb://150.95.82.125:27018/logdb
      - mxgw_domain=https://mxgw.omnicloudapi.com
      - dev_email=jsthtet96@gmail.com